# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nuvemonline.nuvemworks
PackageVersion: 0.4.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{84A6E5F4-7D5A-4762-9A88-31BB0A43E26D}'
AppsAndFeaturesEntries:
- DisplayName: nuvem.works
  Publisher: nuvem.online
  DisplayVersion: 0.4.3
  ProductCode: '{84A6E5F4-7D5A-4762-9A88-31BB0A43E26D}'
  UpgradeCode: '{378B640C-3F14-4A53-A13E-B7C96F522ECB}'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\nuvem.works'
Installers:
- Architecture: x64
  InstallerUrl: https://api.nuvem.works/api/desktop/download?asset=windows-x64&version=0.4.3
  InstallerSha256: ED690B282C8F78D94D43E40ABAABCDAEBB62477A6CE83E7FC8AA890A8F6B3EF4
ManifestType: installer
ManifestVersion: 1.12.0
